# Generated by Django 3.1.3 on 2021-04-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("birth_date", models.DateField()),
            ],
        ),
    ]
