version: '3.8'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - payments-manager-django-db:/var/lib/mysql
    ports:
      - 33066:3306

  backend:
    image: payments_manager_django:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    image: payments_manager_django:dev
    command: 'python -u consumer.py'
    depends_on:
      - db

volumes:
  payments-manager-django-db:

networks:
    default:
        external:
            name: payments_manager_django_network
