version: '3.8'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - payments-manager-flask-db:/var/lib/mysql
    ports:
      - 33067:3306 

  backend:
    image: payments_manager_flask:dev
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  queue:
    image: payments_manager_flask:dev
    command: 'python -u consumer.py'
    depends_on:
      - db

volumes:
  payments-manager-flask-db:

networks:
    default:
        external:
            name: payments_manager_flask_network
